# Unordered list style
MD004:
  style: dash

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced

MD013:
  code_blocks: false
  tables: false

MD033:
  allowed_elements:
    - br
