name: Tagpr
on:
  push:
    branches:
    - main

permissions:
  contents: none

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ vars.APP_ID_TAGPR }}
          private-key: ${{ secrets.PRIVATE_KEY_TAGPR }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Tagpr
        id: tagpr
        uses: tapihdev/actionshub/Songmu/tagpr@main
        with:
          github-token: ${{ steps.token.outputs.token }}

      - name: Annotate major and minor tags
        if: steps.tagpr.outputs.tag != ''
        uses: tapihdev/tag-major-minor-semver@7b86820b4c4e796f6703c551c55ff8f42e165e3a # v1.0.5
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
